### ISSUE TITLE
Can't build because of missing script

### ISSUE THREAD

**Issue by pixelmanya** [DmacMcgreg/Component-Library-Monorepo-Template-RollupJS-Lerna-Yarn-Workspaces#1]
I checked out your repository and tried to run `npm run build` but it failed because of

`Error: Cannot find module './parseArgs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
    at Function.Module._load (internal/modules/cjs/loader.js:535:25)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/dmertz/Documents/Development/packages/Component-Library-Monorepo-Template-RollupJS-Lerna-Yarn-Workspaces/scripts/utils/getPackageNames.js:4:56)`

It seems like you forgot to add `scripts/utils/parseArgs.js` ;)

**Comment by DmacMcgreg** [comment]
You're right.
We need to add it!
I'll have a PR open soon, but if you're in a hurry to get it working, take
a look here to copy over what you might need:
https://github.com/telus/tds-core/blob/master/scripts/utils/parseArgs.js

**Comment by DmacMcgreg** [comment]
Fixed
